version: '3.0'

services:
  pihole:
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8080:80
      - 8443:443
    environment:
      ServerIP: "${IP}"
      ServerIPv6: "${IPv6}"
    volumes:
      - "${DOCKER_CONFIGS}/pihole/:/etc/pihole/"
      - "${DOCKER_CONFIGS}/dnsmasq.d/:/etc/dnsmasq.d/"
restart: unless-stopped
